### PR TITLE
fix client url, live-reload, and added watch script

### LINKED ISSUE #35: Fetch the right version of preview.[hash].js
We need to fetch `https://client.decentraland.today/assets.json` to get the latest version of `preview` and inject a script tag with it.

### PR DESCRIPTION
**Pull request by cazala**
Fixes #35 and #42, I also added a `watch` script that we can run after the first `npm run build` to do incremental compilations (it doesn't rebuild the linker tho, for that one we need to re-run `npm run build` after we make changes to it).

### CODE REVIEW

File: src/utils/generate-html.ts [hunk 1]
```diff
@@ -1,26 +1,31 @@
+import axios from 'axios'
+
 interface GeneratorSettings {
   withSampleScene?: boolean;
 }
 
-export function generateHtml({ withSampleScene = false }: GeneratorSettings): string {
+export async function generateHtml({ withSampleScene = false }: GeneratorSettings): string {
```
Comment (michaltakac) [inline src/utils/generate-html.ts]: please update return type `string` -> `Promise<string>`.
