### PR TITLE
fix: ensure that the process exit after command

### LINKED ISSUE #347: Exit process on deployment success
Currently the process is not exited on deployment success

### PR DESCRIPTION
**Pull request by fmiras**
Fixes #347

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -131,4 +131,4 @@ async function main() {
   }
 }
 
-main()
+main().then(() => process.exit(0))
```
Comment (menduz) [inline src/index.ts]:
```suggestion
main()
  .then(() => process.exit(0))
  .catch((err) => {
    // do something with the error
    process.exit(1)
  })
```
