### PR TITLE
fix: `dcl info` for negative X coords

### LINKED ISSUE #345: `dcl info` with negative X coords not working
# What? 
When executing for example `dcl info -12,-40` the CLI throw an error because it only parse the first digit as a flag 

# Why? 
Because we're not handling `arg` flag parsing

### PR DESCRIPTION
**Pull request by fmiras**
Fixes #345 and #336

### CODE REVIEW

File: src/commands/info.ts [hunk 1]
```diff
@@ -37,12 +37,41 @@ export const help = () => `
       ${chalk.green('$ dcl info 0x8bed95d830475691c10281f1fea2c0a0fe51304b')}
 `
 
+function getTarget(args) {
```
Comment (m-sossich) [inline src/commands/info.ts]: Why not define a  _--target_ parameter?  I mean instead of doing this custom arg parsing.

Something like: dcl info --target=-18,40

Comment (fmiras) [reply src/commands/info.ts]: For many reasons:
1) I think that we have to design the command regardless of the technologies that we're using, and in this case, I think that is more intuitive to set the target as an "arg" instead of as an "option".
2) Flags in CLI are use `--like this` and not `--like=this` to support that we should change `arg` as dependency and find another library or make a big refactor or just make a ugly parsing similar like this one.

File: src/commands/info.ts.rej [hunk 2]
```diff
@@ -0,0 +1,5 @@
+diff a/src/commands/info.ts b/src/commands/info.ts	(rejected hunks)
+@@ -76,2 +78 @@ export async function main() {
+-    contentServerUrl:
+-      args['--host'] || 'https://content.decentraland.org'
++    contentServerUrl: args['--host'] || 'https://content.decentraland.org'
```
Comment (menduz) [inline src/commands/info.ts.rej]: ?

**Comment by fmiras** [comment]
@menduz good point! https://github.com/decentraland/cli/issues/352
